// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: dev/warashi/muscat/v1/muscat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uri         *string                `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpenRequest) GetUri() string {
	if x != nil {
		if x.xxx_hidden_Uri != nil {
			return *x.xxx_hidden_Uri
		}
		return ""
	}
	return ""
}

func (x *OpenRequest) SetUri(v string) {
	x.xxx_hidden_Uri = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *OpenRequest) HasUri() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpenRequest) ClearUri() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uri = nil
}

type OpenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uri *string
}

func (b0 OpenRequest_builder) Build() *OpenRequest {
	m0 := &OpenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uri != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Uri = b.Uri
	}
	return m0
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type OpenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 OpenResponse_builder) Build() *OpenResponse {
	m0 := &OpenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CopyRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body        []byte                 `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CopyRequest) GetBody() []byte {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *CopyRequest) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Body = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CopyRequest) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CopyRequest) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Body = nil
}

type CopyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Body []byte
}

func (b0 CopyRequest_builder) Build() *CopyRequest {
	m0 := &CopyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CopyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CopyResponse_builder) Build() *CopyResponse {
	m0 := &CopyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PasteRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasteRequest) Reset() {
	*x = PasteRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteRequest) ProtoMessage() {}

func (x *PasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PasteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PasteRequest_builder) Build() *PasteRequest {
	m0 := &PasteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PasteResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body        []byte                 `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PasteResponse) Reset() {
	*x = PasteResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteResponse) ProtoMessage() {}

func (x *PasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PasteResponse) GetBody() []byte {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *PasteResponse) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Body = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PasteResponse) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PasteResponse) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Body = nil
}

type PasteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Body []byte
}

func (b0 PasteResponse_builder) Build() *PasteResponse {
	m0 := &PasteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HealthRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HealthRequest_builder) Build() *HealthRequest {
	m0 := &HealthRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type HealthResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pid         int64                  `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthResponse) GetPid() int64 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *HealthResponse) SetPid(v int64) {
	x.xxx_hidden_Pid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *HealthResponse) HasPid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HealthResponse) ClearPid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pid = 0
}

type HealthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pid *int64
}

func (b0 HealthResponse_builder) Build() *HealthResponse {
	m0 := &HealthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pid = *b.Pid
	}
	return m0
}

type GetInputMethodRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInputMethodRequest) Reset() {
	*x = GetInputMethodRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputMethodRequest) ProtoMessage() {}

func (x *GetInputMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetInputMethodRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetInputMethodRequest_builder) Build() *GetInputMethodRequest {
	m0 := &GetInputMethodRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetInputMethodResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetInputMethodResponse) Reset() {
	*x = GetInputMethodResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputMethodResponse) ProtoMessage() {}

func (x *GetInputMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInputMethodResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetInputMethodResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetInputMethodResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetInputMethodResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetInputMethodResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetInputMethodResponse_builder) Build() *GetInputMethodResponse {
	m0 := &GetInputMethodResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type SetInputMethodRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetInputMethodRequest) Reset() {
	*x = SetInputMethodRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInputMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputMethodRequest) ProtoMessage() {}

func (x *SetInputMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetInputMethodRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SetInputMethodRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SetInputMethodRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetInputMethodRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type SetInputMethodRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 SetInputMethodRequest_builder) Build() *SetInputMethodRequest {
	m0 := &SetInputMethodRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type SetInputMethodResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Before      *string                `protobuf:"bytes,1,opt,name=before" json:"before,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetInputMethodResponse) Reset() {
	*x = SetInputMethodResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInputMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputMethodResponse) ProtoMessage() {}

func (x *SetInputMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetInputMethodResponse) GetBefore() string {
	if x != nil {
		if x.xxx_hidden_Before != nil {
			return *x.xxx_hidden_Before
		}
		return ""
	}
	return ""
}

func (x *SetInputMethodResponse) SetBefore(v string) {
	x.xxx_hidden_Before = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SetInputMethodResponse) HasBefore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetInputMethodResponse) ClearBefore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Before = nil
}

type SetInputMethodResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Before *string
}

func (b0 SetInputMethodResponse_builder) Build() *SetInputMethodResponse {
	m0 := &SetInputMethodResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Before != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Before = b.Before
	}
	return m0
}

// PortForwardRequest.body is a body of transfered data.
type PortForwardRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body        []byte                 `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PortForwardRequest) Reset() {
	*x = PortForwardRequest{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRequest) ProtoMessage() {}

func (x *PortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardRequest) GetBody() []byte {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *PortForwardRequest) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Body = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PortForwardRequest) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PortForwardRequest) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Body = nil
}

type PortForwardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Body []byte
}

func (b0 PortForwardRequest_builder) Build() *PortForwardRequest {
	m0 := &PortForwardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

// PortForwardResponse.body is a body of transfered data.
type PortForwardResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body        []byte                 `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PortForwardResponse) Reset() {
	*x = PortForwardResponse{}
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardResponse) ProtoMessage() {}

func (x *PortForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_warashi_muscat_v1_muscat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardResponse) GetBody() []byte {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *PortForwardResponse) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Body = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PortForwardResponse) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PortForwardResponse) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Body = nil
}

type PortForwardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Body []byte
}

func (b0 PortForwardResponse_builder) Build() *PortForwardResponse {
	m0 := &PortForwardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

var File_dev_warashi_muscat_v1_muscat_proto protoreflect.FileDescriptor

var file_dev_warashi_muscat_v1_muscat_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x65, 0x76, 0x2f, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2f, 0x6d, 0x75,
	0x73, 0x63, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68,
	0x69, 0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x1f, 0x0a, 0x0b, 0x4f,
	0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x0e, 0x0a, 0x0c,
	0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x0a, 0x0b,
	0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x0e, 0x0a, 0x0c, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x0e, 0x0a, 0x0c, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x23, 0x0a, 0x0d, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15,
	0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x50, 0x6f, 0x72, 0x74, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0xa8, 0x05, 0x0a,
	0x0d, 0x4d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77,
	0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73,
	0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x22, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73, 0x63,
	0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e,
	0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x04, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x22,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73,
	0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69,
	0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x54, 0x0a, 0x05, 0x50, 0x61, 0x73,
	0x74, 0x65, 0x12, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69,
	0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x73, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61,
	0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x6d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e,
	0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75,
	0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d,
	0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73,
	0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a,
	0x0b, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x29, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x77, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61,
	0x72, 0x61, 0x73, 0x68, 0x69, 0x2e, 0x6d, 0x75, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x61, 0x72, 0x61, 0x73, 0x68, 0x69, 0x2f, 0x6d, 0x75,
	0x73, 0x63, 0x61, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x62, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var file_dev_warashi_muscat_v1_muscat_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dev_warashi_muscat_v1_muscat_proto_goTypes = []any{
	(*OpenRequest)(nil),            // 0: dev.warashi.muscat.v1.OpenRequest
	(*OpenResponse)(nil),           // 1: dev.warashi.muscat.v1.OpenResponse
	(*CopyRequest)(nil),            // 2: dev.warashi.muscat.v1.CopyRequest
	(*CopyResponse)(nil),           // 3: dev.warashi.muscat.v1.CopyResponse
	(*PasteRequest)(nil),           // 4: dev.warashi.muscat.v1.PasteRequest
	(*PasteResponse)(nil),          // 5: dev.warashi.muscat.v1.PasteResponse
	(*HealthRequest)(nil),          // 6: dev.warashi.muscat.v1.HealthRequest
	(*HealthResponse)(nil),         // 7: dev.warashi.muscat.v1.HealthResponse
	(*GetInputMethodRequest)(nil),  // 8: dev.warashi.muscat.v1.GetInputMethodRequest
	(*GetInputMethodResponse)(nil), // 9: dev.warashi.muscat.v1.GetInputMethodResponse
	(*SetInputMethodRequest)(nil),  // 10: dev.warashi.muscat.v1.SetInputMethodRequest
	(*SetInputMethodResponse)(nil), // 11: dev.warashi.muscat.v1.SetInputMethodResponse
	(*PortForwardRequest)(nil),     // 12: dev.warashi.muscat.v1.PortForwardRequest
	(*PortForwardResponse)(nil),    // 13: dev.warashi.muscat.v1.PortForwardResponse
}
var file_dev_warashi_muscat_v1_muscat_proto_depIdxs = []int32{
	6,  // 0: dev.warashi.muscat.v1.MuscatService.Health:input_type -> dev.warashi.muscat.v1.HealthRequest
	0,  // 1: dev.warashi.muscat.v1.MuscatService.Open:input_type -> dev.warashi.muscat.v1.OpenRequest
	2,  // 2: dev.warashi.muscat.v1.MuscatService.Copy:input_type -> dev.warashi.muscat.v1.CopyRequest
	4,  // 3: dev.warashi.muscat.v1.MuscatService.Paste:input_type -> dev.warashi.muscat.v1.PasteRequest
	8,  // 4: dev.warashi.muscat.v1.MuscatService.GetInputMethod:input_type -> dev.warashi.muscat.v1.GetInputMethodRequest
	10, // 5: dev.warashi.muscat.v1.MuscatService.SetInputMethod:input_type -> dev.warashi.muscat.v1.SetInputMethodRequest
	12, // 6: dev.warashi.muscat.v1.MuscatService.PortForward:input_type -> dev.warashi.muscat.v1.PortForwardRequest
	7,  // 7: dev.warashi.muscat.v1.MuscatService.Health:output_type -> dev.warashi.muscat.v1.HealthResponse
	1,  // 8: dev.warashi.muscat.v1.MuscatService.Open:output_type -> dev.warashi.muscat.v1.OpenResponse
	3,  // 9: dev.warashi.muscat.v1.MuscatService.Copy:output_type -> dev.warashi.muscat.v1.CopyResponse
	5,  // 10: dev.warashi.muscat.v1.MuscatService.Paste:output_type -> dev.warashi.muscat.v1.PasteResponse
	9,  // 11: dev.warashi.muscat.v1.MuscatService.GetInputMethod:output_type -> dev.warashi.muscat.v1.GetInputMethodResponse
	11, // 12: dev.warashi.muscat.v1.MuscatService.SetInputMethod:output_type -> dev.warashi.muscat.v1.SetInputMethodResponse
	13, // 13: dev.warashi.muscat.v1.MuscatService.PortForward:output_type -> dev.warashi.muscat.v1.PortForwardResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_dev_warashi_muscat_v1_muscat_proto_init() }
func file_dev_warashi_muscat_v1_muscat_proto_init() {
	if File_dev_warashi_muscat_v1_muscat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dev_warashi_muscat_v1_muscat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dev_warashi_muscat_v1_muscat_proto_goTypes,
		DependencyIndexes: file_dev_warashi_muscat_v1_muscat_proto_depIdxs,
		MessageInfos:      file_dev_warashi_muscat_v1_muscat_proto_msgTypes,
	}.Build()
	File_dev_warashi_muscat_v1_muscat_proto = out.File
	file_dev_warashi_muscat_v1_muscat_proto_rawDesc = nil
	file_dev_warashi_muscat_v1_muscat_proto_goTypes = nil
	file_dev_warashi_muscat_v1_muscat_proto_depIdxs = nil
}
